FUSETOOLS2-1807: Add test for creating Maven, CTD and Launch grouped …
camel-tooling/camel-dap-client-eclipse pull request #40
Opened 2023-01-06 16:35 UTC by pospisilf

…configurations

2023-01-09 09:25 UTC, apupier reviewed
- is it normal to have some .class?

2023-01-09 15:20 UTC, apupier commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/plugins/com.github.cameltooling.dap.reddeer/src/com/github/cameltooling/dap/reddeer/dialog/DebugConfigurationDialog.java
> +		// open debug configurations
if I read well, we can factorize this part of code with a single parameter. It will also allow to give a descriptive method name to remove need of the comment.

2023-01-09 15:20 UTC, apupier commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/CreatingConfigurationsTest.java
> +public class CreatingConfigurationsTest {
Shouldn't we delete the created launch configurations in teardown to avoid potential interaction with other tests?

2023-01-10 14:54 UTC, djelinek requested changes

2023-01-10 14:54 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/resources/camel-examples/main-xml/pom.xml
> +      <version>3.20.0</version>
you can use placeholder `${project.version}` for dependencies with 3.20.0 version to easier maintenance in future

2023-01-10 14:54 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/CreatingConfigurationsTest.java
> +public class CreatingConfigurationsTest {
I agree. `@AfterClass` with some cleanup could be useful here

2023-01-17 19:59 UTC, apupier approved these changes

2023-01-18 09:55 UTC, djelinek requested changes

2023-01-18 09:55 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/plugins/com.github.cameltooling.dap.reddeer/src/com/github/cameltooling/dap/reddeer/views/DebugView.java
> +				System.out.println("Konfigurace nalezena.");
unnecessary console log :-)

2023-01-18 10:49 UTC, djelinek approved these changes

2023-01-18 10:49 UTC, merged