FUSETOOLS2-1776: Add test for debugging Camel DSL
camel-tooling/camel-dap-client-eclipse pull request #47
Opened 2023-02-20 11:13 UTC by pospisilf

2023-02-20 14:49 UTC, djelinek requested changes
please remove `bin/` folders in examples which contains compiled .class files

2023-02-20 14:49 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/DebuggingCamelDSLsTest.java
> +//import org.eclipse.reddeer.requirements.cleanworkspace.CleanWorkspaceRequirement;
remove commented import

2023-02-20 14:49 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/plugins/com.github.cameltooling.dap.reddeer/src/com/github/cameltooling/dap/reddeer/dialog/RunConfigurationDialog.java
> +	 * TODO
not finished TODO comments in whole class

2023-02-20 22:14 UTC, djelinek requested changes

2023-02-27 09:31 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/CreatingConfigurationsTest.java
> +	new DebugConfigurationDialog().createCTD(CTD_CONF);
wrong indent?

2023-02-27 09:31 UTC, djelinek commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/DebuggingCamelDSLsTest.java
> +	private static final String GTE = "Generic Text Editor";
maybe could be moved to Generic Editor class?

2023-02-27 09:53 UTC, pospisilf commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/DebuggingCamelDSLsTest.java
> +	private static final String GTE = "Generic Text Editor";
Good idea!

2023-02-27 09:53 UTC, pospisilf commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/CreatingConfigurationsTest.java
> +	new DebugConfigurationDialog().createCTD(CTD_CONF);
Yes... :-(

2023-02-27 10:49 UTC, djelinek approved these changes

2023-02-28 08:05 UTC, apupier commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/DebuggingCamelDSLsTest.java
> +	private void waitUntilVariableIsLoaded() {
using the SWTBot bot.waitUntil seems to be better as it will allow a better error reporting in case of problems or with the WaitUntil from Reddeer https://www.vogella.com/tutorials/EclipseRedDeer/article.html#wait-conditions

2023-02-28 08:05 UTC, apupier commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/plugins/com.github.cameltooling.dap.reddeer/src/com/github/cameltooling/dap/reddeer/views/DebugView.java
> +		variables.open();
would be better to use a SWtBot bot.waitUntil or a Reddeer WaitUntil

2023-03-02 10:26 UTC, pospisilf commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/tests/com.github.cameltooling.dap.ui.tests/src/com/github/cameltooling/dap/ui/tests/DebuggingCamelDSLsTest.java
> +			AbstractWait.sleep(TimePeriod.getCustom(3));
Reaction of IDE is sometimes slow, pushing Step Over button more times without wait becomes to huge instability, this is best effort solution in my opinion.

2023-03-02 10:53 UTC, pospisilf commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/plugins/com.github.cameltooling.dap.reddeer/META-INF/MANIFEST.MF
> + org.eclipse.swt,
You are right.

2023-03-02 10:53 UTC, pospisilf commented on com.github.camel-tooling.dap.eclipse.client.tests.ui/plugins/com.github.cameltooling.dap.reddeer/src/com/github/cameltooling/dap/reddeer/views/DebugView.java
> +		variables.open();
With WaitUntil condition seems waiting here unnecessary.

2023-03-06 16:35 UTC, merged